### ISSUE TITLE
Any documentation or client sample in reading sensor value from a UA Server

### ISSUE THREAD

**Issue by irwantantu** [OPCFoundation/UA-Java#109]
I have ran the OPC UA SampleClient and it works and connected to the UA Server, but I can not understand how to get the value from the KepServerX from Kepware. The browse cameback with the 3 references. How that related to the tag points in the KepServerX where it defines 2 tags value in a device.. I used kepware UA Interface..
This is the first time I am using the OPC UA.. Any advise?

**Comment by bjakke** [comment]
Like I mentioned in the previous issue that I closed ( #108 ) these kind of questions are outside the scope of the/this stack.

In general, the stack is not the best place to start. Usually the stacks are low-level components to SDK level frameworks, which do more than the bare request/response handling. Even with those it is best you are familiar with the specification, please read it: https://opcfoundation.org/developer-tools/specifications-unified-architecture. If you are just using the request/response layer, which what this stack is, they you definitely need to know what they do (because all their parameters, purposes e.g. are explained there (part 4)).

In addition you need to know or discovery via Browsing on how the AddressSpace looks like. Typically this is explained in a server product manual. Or alternatively via graphical clients.

You can read e.g. https://opcfoundation.org/wp-content/uploads/2017/11/OPC-UA-Interoperability-For-Industrie4-and-IoT-EN.pdf p.33 on stack vs toolkits/SDKs
