### ISSUE TITLE
SecurityMode.ALL should equal to SecurityMode.ALL_102

### ISSUE THREAD

**Issue by jouniaro** [OPCFoundation/UA-Java#121]
It has been left to equal to ALL_101 so far, since support for BASIC256SHA256 has not been common in other apps.

But I think it would be safe to equal it to ALL_102 finally. And maybe, we could have ALL_103 as well, which would equal to ALL_102, though.

**Comment by bjakke** [comment]
Per #163, I would say the ALL constant should maybe be removed and only have constants ALL_101,102,103,104 and SECURE_101,102,103,104. Those modes that are marked deprecated should maybe be only explicitly selected, which is why I would say it is better to only have version-specific constants. Another way is to make the ALL constant Deprecated for now (as it would include deprecated modes in 1.04).

Alternatively something like "ALL_NOT_DEPRECATED" could maybe be created that would always point to the latest number of the combinations (i.e. in 1.04 it would point to ALL_104).

Also one option would be to remove/deprecate completely the ALL constants and only provide SECURE ones (that could be then used in combination with the NONE constant). This would avoid making almost the same list twice.

However most of the interop testing is done using the BASIC128RSA15 mode so in practice most applications have to support it.
