### ISSUE TITLE
"How to run" section is README.md is missing

### ISSUE THREAD

**Issue by wiewioraseb** [OPCFoundation/UA-Java#143]
Hello, I find running this project challenging. "How to run" section in README.md is missing. This repository consists of some sub programs, examples, server/clients, code generation etc.  
I would be very grateful if you could add few simple points to follow to make this run, so someone like me would have to go dive deep into the repo.

Thank you in advance for your contribution.

**Comment by bjakke** [comment]
Hi,

Please note that this is a (low-level abstraction layer) software library (for OPC UA in java), in general you do not "run" them, but use them as dependencies for higher level libraries or applications. Other parts of repo are examples and helper tools used to make this lib.

The main README refers to the examples' readme https://github.com/OPCFoundation/UA-Java#examples (but the link is a bit off since it is from the era before different sample folders), therefore please read the readme from https://github.com/OPCFoundation/UA-Java/tree/master/examples/basic. Also the https://github.com/OPCFoundation/UA-Java#notes-for-developers explains other parts. 

In general you need to have or learn deep knowledge of OPC UA (and java for this repo) before using this library, since most terms/apis are 1:1 from the UA specification (https://opcfoundation.org/developer-tools/specifications-unified-architecture). Note that this Stack implements UA 1.03 communication layer (making connection and certificate handling), but e.g. making a Session is outside of the library code, but the actual apis for ServiceRequests of UA are part of the lib (for session CreateSessionRequest/Response), please refer to the specification Part 4 for definition of those.
