### ISSUE TITLE
EncodeableSerializer / Serializer Composition not dynamic friendly

### ISSUE THREAD

**Issue by bdorninger** [OPCFoundation/UA-Java#144]
Using OPC UA SDK 1.03.0342.0
We have a special generic serializer, which is capable of dynamic additions / removals of support for structures. Suitable for an environment, where strucutres and serialization support may may come and go at runtime (e.g. plugging in a device, that provides a new UA model)).
We are experiencing some limitations:

1. late additions of supported structs
Need to call EncodeableSerializer.getInstance().addSerializer(ourSpecialDynamicSerializer);
to tell EncodeableSerializer of late additions of supported structures.
SerializerComposition asks our serializer for supported classes, which of course returns new ones as well as already added ones. This poses no problems during operation so far (mappings are overwritten), however in case of running unit tests, the assertion
assert(classToBinId.get(clazz)==null);
fires at the first "old" class.
IMHO, this assertion should either not be there or ensure the existing mapping clazz <-> binID is either null or identical to the newly proposed one.
If the mapping clazz <-> binId is identical, the subsequent put operations may be skipped.

Request: Remove or adapt this assertion

2. no removal of serializers possible
The EncodeableSerializer/Composition interface is a little limited. It just allows adding serializers, but one cannot query capabilites/serializers or remove serializers

Request: add at least support to remove serializers

Regards,
Bernhard

**Comment by bjakke** [comment]
Hi,

Good points. In general there is a lot of things that would require an overhaul, which is not a reality in short term. Removing the assert is however something that can be done easily.

In general the stack only supports the standard namespace structures and anything else is out of scope, however since the stack handles the serialization, there should be a better mechanism for this.

Most likely the better solution would be if you create your own IEncodeableSerializer implementation and make it delegate to the EncodeableSerializer.getInstance() when needed. This way you could somewhat add more dynamic support. If you find the EncoderContext you are using to encode/decode you can set the serializer via EncoderContext.setEncodeableSerializer.

**Comment by bdorninger** [comment]
Hi!
Thanks for your quick answer pointing out a possible solution. I will look into creation and usage of EncoderContext within the UA impl our application relies on.
If you would remove/adapt that assert statement in the near future, it would be great though.
Regards,
Bernhard
