### ISSUE TITLE
NodeClass#getSet() is incorrect when mask == 0 (Mantis 2710)

### ISSUE THREAD

**Issue by dk2129** [OPCFoundation/UA-Java#15]
When mask==0 only NodeClass.Unspecified is returned. EnumSet.allOf(...) should be returned instead.

**Comment by jouniaro** [comment]
WILL NOT CHANGE

Browse service indeed defines that if nodeClassMask==0, it means that all node classes are to be returned.

However, all other enumerations are defined to return NONE, if the respective mask==0, so to be consistent, we should not return ALL for NodeClass, just because of this one service definition.

On the other hand, Unspecified is not a defined NodeClass and should be considered to be removed from the stack. When NodeClass is not defined for some nodes, it should be null, instead. See #49
